# EMULATOR CONFIG
EMULATOR_SPEED_HEADLESS = 0
EMULATOR_SPEED_FULL = 5
EMULATOR_TICK_HOLD = 20
EMULATOR_TICK_RELEASE = 2

# EMULATOR PATH
PATH_ROM = "emulator/red.gb"
PATH_START_SAVE = "emulator/bw_squirtle.save"

# RUN CONFIG
EPISODE_SIZE = 25000
BATCH_SIZE = 10
