[project]
authors = ["ashruidan <ashruidan@github.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pokefang"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<4"
numpy = ">=2.1.3,<3"


[pypi-dependencies]
pyboy = "~=2.4.0"
